name: sqldb_simple

# Manual trigger
on:
  workflow_dispatch:

# Example of trigger on push
# on: 
#  push:
  
env:
    AZURE_RESOURCEGROUP_NAME: DataSatPN_2022_Demo_DEV

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checks out a copy of the repo on a ubuntu-latest runner
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZCRED_DEV }}
    
    #Deploy template -- with marketplace action
    - name: Deploy template
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./BicepFiles/Modular_BicepRegistry/APP1-main-noAlias.bicep
        parameters: ./BicepFiles/Modular_BicepRegistry/APP1-DEV.parameters.json
